version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
    server:
        build: ./server
        command: ./main
        ports:
            - "8080:3000"
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
