version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
    server:
        build: ./server
        command: ./main
        ports:
            # by default gin runs on 3001
            - "8080:3001"
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
